### ISSUE TITLE
Not an issue, just an idea

### ISSUE THREAD

**Issue by juancpgo** [jannisg/statamic-pagereorder#5] opened 2014-06-16 22:48 UTC
Sorry, this is not an issue, just an idea.

Currently if we need to change the position number of entries (when not ordered by date) we have to (1) open the entry, (2) change the position field and (3) save and fix the numbering conflicts since now we have number duplicity. Quite puzzling and annoying for the user. It would be 100 times better and smarter to have a drag and drop mode to quickly change the ordering of entries. In my projects, ordering entries are always more important than ordering pages. That because the webdesigner is supposed to create the layout, which includes the page ordering. 90% of clients are never like: "Oh, I think I want to put the About Us page first". Usually they don't even think about page ordering. But the entries are inserted by the client, so he should be able to quickly reorder them as he pleases. For example, reorder the slides in the home page, or a restaurant manager reorder dishes in the food menu page.

**Comment by jannisg** [comment] 2015-01-09 08:50
Duplicate of #3.

Thanks for the comment.

**Closed by jannisg** 2015-01-09 08:50 UTC
